const model = {
	sort: {
		field: null,
		direction: null,
	},
	paging: {
		size: 10,
		index: 0,
	},
	filter: {
		continents: [],
		continent: null,
	},
	costStats: [
		{
			Country: "Costa Rica",
			"Meal, Inexpensive Restaurant": 101.72,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 610.34,
			"Domestic Beer  (0.5 liter draught)": 30.52,
			"Gasoline  (1 liter)": 16.48,
			"Apartment  (1 bedroom)  in City Centre": 6503.66,
			"Apartment  (1 bedroom)  Outside of Centre": 4415.75,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 835.18,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 532.69,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 228.58,
		},
		{
			Country: "Portugal",
			"Meal, Inexpensive Restaurant": 103.41,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 459.58,
			"Domestic Beer  (0.5 liter draught)": 22.98,
			"Gasoline  (1 liter)": 21.35,
			"Apartment  (1 bedroom)  in City Centre": 9094.98,
			"Apartment  (1 bedroom)  Outside of Centre": 6954.94,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1256.57,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 407.42,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 214.27,
		},
		{
			Country: "Belarus",
			"Meal, Inexpensive Restaurant": 106.82,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 427.28,
			"Domestic Beer  (0.5 liter draught)": 13.41,
			"Gasoline  (1 liter)": 10.58,
			"Apartment  (1 bedroom)  in City Centre": 3858.45,
			"Apartment  (1 bedroom)  Outside of Centre": 2453.23,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 675.66,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 142.96,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 121.9,
		},
		{
			Country: "Croatia",
			"Meal, Inexpensive Restaurant": 107.32,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 534.09,
			"Domestic Beer  (0.5 liter draught)": 30.42,
			"Gasoline  (1 liter)": 17.68,
			"Apartment  (1 bedroom)  in City Centre": 5555.62,
			"Apartment  (1 bedroom)  Outside of Centre": 4277.33,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1813.6,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 273.78,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 235.65,
		},
		{
			Country: "Georgia",
			"Meal, Inexpensive Restaurant": 110.77,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 410.26,
			"Domestic Beer  (0.5 liter draught)": 18.46,
			"Gasoline  (1 liter)": 13.41,
			"Apartment  (1 bedroom)  in City Centre": 7984.78,
			"Apartment  (1 bedroom)  Outside of Centre": 5504.44,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 768.22,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 207.54,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 100.74,
		},
		{
			Country: "Latvia",
			"Meal, Inexpensive Restaurant": 114.9,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 574.48,
			"Domestic Beer  (0.5 liter draught)": 39.06,
			"Gasoline  (1 liter)": 19.8,
			"Apartment  (1 bedroom)  in City Centre": 4345.03,
			"Apartment  (1 bedroom)  Outside of Centre": 3054.86,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 3478.48,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 188.05,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 186.87,
		},
		{
			Country: "Estonia",
			"Meal, Inexpensive Restaurant": 114.9,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 654.9,
			"Domestic Beer  (0.5 liter draught)": 51.7,
			"Gasoline  (1 liter)": 19.9,
			"Apartment  (1 bedroom)  in City Centre": 6461.36,
			"Apartment  (1 bedroom)  Outside of Centre": 4761.95,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2713.53,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 284.91,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 249.49,
		},
		{
			Country: "Slovenia",
			"Meal, Inexpensive Restaurant": 114.9,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 517.03,
			"Domestic Beer  (0.5 liter draught)": 32.17,
			"Gasoline  (1 liter)": 17.14,
			"Apartment  (1 bedroom)  in City Centre": 6895.72,
			"Apartment  (1 bedroom)  Outside of Centre": 5500.26,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2591.69,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 383.21,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 102.52,
		},
		{
			Country: "Lithuania",
			"Meal, Inexpensive Restaurant": 114.9,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 574.48,
			"Domestic Beer  (0.5 liter draught)": 49.4,
			"Gasoline  (1 liter)": 18.88,
			"Apartment  (1 bedroom)  in City Centre": 7115,
			"Apartment  (1 bedroom)  Outside of Centre": 4739.2,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2197.47,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 156.77,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 159.79,
		},
		{
			Country: "Sweden",
			"Meal, Inexpensive Restaurant": 115.63,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 770.85,
			"Domestic Beer  (0.5 liter draught)": 69.38,
			"Gasoline  (1 liter)": 19.52,
			"Apartment  (1 bedroom)  in City Centre": 8782.17,
			"Apartment  (1 bedroom)  Outside of Centre": 6568.51,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 926.83,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 306.21,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 288.1,
		},
		{
			Country: "Singapore",
			"Meal, Inexpensive Restaurant": 118.51,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 790.07,
			"Domestic Beer  (0.5 liter draught)": 79.01,
			"Gasoline  (1 liter)": 22.76,
			"Apartment  (1 bedroom)  in City Centre": 35396.79,
			"Apartment  (1 bedroom)  Outside of Centre": 23586.56,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1684.4,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 366,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 175.89,
		},
		{
			Country: "Puerto Rico",
			"Meal, Inexpensive Restaurant": 134.61,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 753.84,
			"Domestic Beer  (0.5 liter draught)": 25.58,
			"Gasoline  (1 liter)": 10.64,
			"Apartment  (1 bedroom)  in City Centre": 12167.79,
			"Apartment  (1 bedroom)  Outside of Centre": 6559.04,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2404.42,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 656.56,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 764.61,
		},
		{
			Country: "Greece",
			"Meal, Inexpensive Restaurant": 137.87,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 517.03,
			"Domestic Beer  (0.5 liter draught)": 45.96,
			"Gasoline  (1 liter)": 23.19,
			"Apartment  (1 bedroom)  in City Centre": 4761.49,
			"Apartment  (1 bedroom)  Outside of Centre": 3992.71,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2349.01,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 349.85,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 220.54,
		},
		{
			Country: "Germany",
			"Meal, Inexpensive Restaurant": 137.87,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 689.37,
			"Domestic Beer  (0.5 liter draught)": 45.96,
			"Gasoline  (1 liter)": 22.59,
			"Apartment  (1 bedroom)  in City Centre": 9621.11,
			"Apartment  (1 bedroom)  Outside of Centre": 7160.97,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 3148.23,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 496.42,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 416.69,
		},
		{
			Country: "Spain",
			"Meal, Inexpensive Restaurant": 137.87,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 517.03,
			"Domestic Beer  (0.5 liter draught)": 28.72,
			"Gasoline  (1 liter)": 18.84,
			"Apartment  (1 bedroom)  in City Centre": 8729.71,
			"Apartment  (1 bedroom)  Outside of Centre": 7007.64,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1479.27,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 378.21,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 228.98,
		},
		{
			Country: "Finland",
			"Meal, Inexpensive Restaurant": 143.62,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 919.16,
			"Domestic Beer  (0.5 liter draught)": 80.43,
			"Gasoline  (1 liter)": 24.37,
			"Apartment  (1 bedroom)  in City Centre": 9082.55,
			"Apartment  (1 bedroom)  Outside of Centre": 7446.1,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1312.09,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 234.6,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 308.33,
		},
		{
			Country: "New Zealand",
			"Meal, Inexpensive Restaurant": 159.24,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 764.35,
			"Domestic Beer  (0.5 liter draught)": 63.7,
			"Gasoline  (1 liter)": 17.79,
			"Apartment  (1 bedroom)  in City Centre": 11794.22,
			"Apartment  (1 bedroom)  Outside of Centre": 9801.65,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1436.3,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 547.54,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 412.23,
		},
		{
			Country: "Uruguay",
			"Meal, Inexpensive Restaurant": 169.29,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 564.32,
			"Domestic Beer  (0.5 liter draught)": 42.32,
			"Gasoline  (1 liter)": 22.02,
			"Apartment  (1 bedroom)  in City Centre": 6494.08,
			"Apartment  (1 bedroom)  Outside of Centre": 5030.31,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1513.63,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 432.91,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 153.9,
		},
		{
			Country: "Indonesia",
			"Meal, Inexpensive Restaurant": 17.52,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 175.22,
			"Domestic Beer  (0.5 liter draught)": 28.04,
			"Gasoline  (1 liter)": 8.9,
			"Apartment  (1 bedroom)  in City Centre": 3253.19,
			"Apartment  (1 bedroom)  Outside of Centre": 1978.79,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 670.04,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 302.48,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 32.55,
		},
		{
			Country: "Cyprus",
			"Meal, Inexpensive Restaurant": 172.34,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 689.37,
			"Domestic Beer  (0.5 liter draught)": 34.47,
			"Gasoline  (1 liter)": 17.68,
			"Apartment  (1 bedroom)  in City Centre": 11166.27,
			"Apartment  (1 bedroom)  Outside of Centre": 8374.51,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2082.3,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 387.66,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 233.28,
		},
		{
			Country: "Austria",
			"Meal, Inexpensive Restaurant": 172.34,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 689.37,
			"Domestic Beer  (0.5 liter draught)": 45.96,
			"Gasoline  (1 liter)": 19.82,
			"Apartment  (1 bedroom)  in City Centre": 9444.38,
			"Apartment  (1 bedroom)  Outside of Centre": 7568.47,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 3427.25,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 378.66,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 266.01,
		},
		{
			Country: "Italy",
			"Meal, Inexpensive Restaurant": 172.34,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 689.37,
			"Domestic Beer  (0.5 liter draught)": 57.45,
			"Gasoline  (1 liter)": 22.06,
			"Apartment  (1 bedroom)  in City Centre": 7681.86,
			"Apartment  (1 bedroom)  Outside of Centre": 5959.64,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2258.39,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 318.71,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 164.44,
		},
		{
			Country: "Malta",
			"Meal, Inexpensive Restaurant": 172.34,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 804.27,
			"Domestic Beer  (0.5 liter draught)": 34.47,
			"Gasoline  (1 liter)": 15.52,
			"Apartment  (1 bedroom)  in City Centre": 10222.21,
			"Apartment  (1 bedroom)  Outside of Centre": 8411.84,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1129.68,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 365.68,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 287.14,
		},
		{
			Country: "Netherlands",
			"Meal, Inexpensive Restaurant": 172.34,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 804.27,
			"Domestic Beer  (0.5 liter draught)": 57.45,
			"Gasoline  (1 liter)": 23.4,
			"Apartment  (1 bedroom)  in City Centre": 13784.06,
			"Apartment  (1 bedroom)  Outside of Centre": 11107.01,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2433.72,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 462.98,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 291.29,
		},
		{
			Country: "Ireland",
			"Meal, Inexpensive Restaurant": 172.34,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 919.16,
			"Domestic Beer  (0.5 liter draught)": 63.19,
			"Gasoline  (1 liter)": 20.73,
			"Apartment  (1 bedroom)  in City Centre": 16969.49,
			"Apartment  (1 bedroom)  Outside of Centre": 14314.14,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2379.95,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 561.18,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 232.46,
		},
		{
			Country: "France",
			"Meal, Inexpensive Restaurant": 172.34,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 689.37,
			"Domestic Beer  (0.5 liter draught)": 68.94,
			"Gasoline  (1 liter)": 21.87,
			"Apartment  (1 bedroom)  in City Centre": 8307.83,
			"Apartment  (1 bedroom)  Outside of Centre": 6791.32,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1934.12,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 338.71,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 359.85,
		},
		{
			Country: "Australia",
			"Meal, Inexpensive Restaurant": 173.51,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 832.86,
			"Domestic Beer  (0.5 liter draught)": 69.4,
			"Gasoline  (1 liter)": 13.82,
			"Apartment  (1 bedroom)  in City Centre": 16129.14,
			"Apartment  (1 bedroom)  Outside of Centre": 12708.28,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2226.95,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 604.9,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 309.58,
		},
		{
			Country: "Canada",
			"Meal, Inexpensive Restaurant": 175.35,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 717.33,
			"Domestic Beer  (0.5 liter draught)": 55.79,
			"Gasoline  (1 liter)": 12.86,
			"Apartment  (1 bedroom)  in City Centre": 13515.01,
			"Apartment  (1 bedroom)  Outside of Centre": 11622.81,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1589.7,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 683.94,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 453.3,
		},
		{
			Country: "Pakistan",
			"Meal, Inexpensive Restaurant": 18.16,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 117.15,
			"Domestic Beer  (0.5 liter draught)": "-",
			"Gasoline  (1 liter)": 9.56,
			"Apartment  (1 bedroom)  in City Centre": 1072.02,
			"Apartment  (1 bedroom)  Outside of Centre": 693.93,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 766.32,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 156.18,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 38.93,
		},
		{
			Country: "Bangladesh",
			"Meal, Inexpensive Restaurant": 19.65,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 98.27,
			"Domestic Beer  (0.5 liter draught)": "-",
			"Gasoline  (1 liter)": 11.49,
			"Apartment  (1 bedroom)  in City Centre": 1054.63,
			"Apartment  (1 bedroom)  Outside of Centre": 635.66,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 370.8,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 202.71,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 72.08,
		},
		{
			Country: "Belgium",
			"Meal, Inexpensive Restaurant": 195.32,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 861.71,
			"Domestic Beer  (0.5 liter draught)": 45.96,
			"Gasoline  (1 liter)": 21.27,
			"Apartment  (1 bedroom)  in City Centre": 9373.34,
			"Apartment  (1 bedroom)  Outside of Centre": 7889.69,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2176.28,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 564.47,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 237.98,
		},
		{
			Country: "Israel",
			"Meal, Inexpensive Restaurant": 198.03,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 848.69,
			"Domestic Beer  (0.5 liter draught)": 84.87,
			"Gasoline  (1 liter)": 19.82,
			"Apartment  (1 bedroom)  in City Centre": 11377.09,
			"Apartment  (1 bedroom)  Outside of Centre": 9272.79,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2335.25,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 284.62,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 135.53,
		},
		{
			Country: "Norway",
			"Meal, Inexpensive Restaurant": 200,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 1000,
			"Domestic Beer  (0.5 liter draught)": 99,
			"Gasoline  (1 liter)": 21.42,
			"Apartment  (1 bedroom)  in City Centre": 11330.12,
			"Apartment  (1 bedroom)  Outside of Centre": 9054.22,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2200.15,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 554.14,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 485.33,
		},
		{
			Country: "United Kingdom",
			"Meal, Inexpensive Restaurant": 200.24,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 800.97,
			"Domestic Beer  (0.5 liter draught)": 60.07,
			"Gasoline  (1 liter)": 20.76,
			"Apartment  (1 bedroom)  in City Centre": 12418.9,
			"Apartment  (1 bedroom)  Outside of Centre": 9671.32,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2812.04,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 405.94,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 156.31,
		},
		{
			Country: "Luxembourg",
			"Meal, Inexpensive Restaurant": 212.56,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 829.54,
			"Domestic Beer  (0.5 liter draught)": 57.45,
			"Gasoline  (1 liter)": 18.62,
			"Apartment  (1 bedroom)  in City Centre": 18147.04,
			"Apartment  (1 bedroom)  Outside of Centre": 15017.67,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2709.57,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 563.12,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 258.51,
		},
		{
			Country: "United States",
			"Meal, Inexpensive Restaurant": 215.38,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 807.69,
			"Domestic Beer  (0.5 liter draught)": 64.62,
			"Gasoline  (1 liter)": 10.8,
			"Apartment  (1 bedroom)  in City Centre": 19796.42,
			"Apartment  (1 bedroom)  Outside of Centre": 14915.69,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2055.3,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 760.27,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 494.39,
		},
		{
			Country: "Denmark",
			"Meal, Inexpensive Restaurant": 215.68,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 1078.39,
			"Domestic Beer  (0.5 liter draught)": 77.03,
			"Gasoline  (1 liter)": 22.5,
			"Apartment  (1 bedroom)  in City Centre": 11787.69,
			"Apartment  (1 bedroom)  Outside of Centre": 9359.17,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2260.21,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 376.79,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 223.62,
		},
		{
			Country: "Vietnam",
			"Meal, Inexpensive Restaurant": 22.17,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 221.71,
			"Domestic Beer  (0.5 liter draught)": 11.09,
			"Gasoline  (1 liter)": 11.82,
			"Apartment  (1 bedroom)  in City Centre": 3851.5,
			"Apartment  (1 bedroom)  Outside of Centre": 2450.55,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 680.69,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 110.17,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 63.69,
		},
		{
			Country: "Nepal",
			"Meal, Inexpensive Restaurant": 23.32,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 202.99,
			"Domestic Beer  (0.5 liter draught)": 24.36,
			"Gasoline  (1 liter)": 13.52,
			"Apartment  (1 bedroom)  in City Centre": 1262.64,
			"Apartment  (1 bedroom)  Outside of Centre": 866.95,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 260.56,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 130.28,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 51.64,
		},
		{
			Country: "Algeria",
			"Meal, Inexpensive Restaurant": 23.53,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 196.11,
			"Domestic Beer  (0.5 liter draught)": 15.69,
			"Gasoline  (1 liter)": 3.46,
			"Apartment  (1 bedroom)  in City Centre": 1806.77,
			"Apartment  (1 bedroom)  Outside of Centre": 1134.81,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 413.89,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 265.89,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 134.84,
		},
		{
			Country: "Thailand",
			"Meal, Inexpensive Restaurant": 24.16,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 241.64,
			"Domestic Beer  (0.5 liter draught)": 21.14,
			"Gasoline  (1 liter)": 12.55,
			"Apartment  (1 bedroom)  in City Centre": 4181.69,
			"Apartment  (1 bedroom)  Outside of Centre": 2533.21,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 761.15,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 175.3,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 158.23,
		},
		{
			Country: "Sri Lanka",
			"Meal, Inexpensive Restaurant": 25.03,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 166.85,
			"Domestic Beer  (0.5 liter draught)": 16.68,
			"Gasoline  (1 liter)": 13.03,
			"Apartment  (1 bedroom)  in City Centre": 2201.36,
			"Apartment  (1 bedroom)  Outside of Centre": 1276.14,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 439.02,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 129,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 61.53,
		},
		{
			Country: "India",
			"Meal, Inexpensive Restaurant": 25.91,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 129.56,
			"Domestic Beer  (0.5 liter draught)": 20.73,
			"Gasoline  (1 liter)": 13.56,
			"Apartment  (1 bedroom)  in City Centre": 2010.22,
			"Apartment  (1 bedroom)  Outside of Centre": 1286.96,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 434.95,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 90.41,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 40.85,
		},
		{
			Country: "Tunisia",
			"Meal, Inexpensive Restaurant": 27.34,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 170.86,
			"Domestic Beer  (0.5 liter draught)": 13.67,
			"Gasoline  (1 liter)": 7.67,
			"Apartment  (1 bedroom)  in City Centre": 2064.68,
			"Apartment  (1 bedroom)  Outside of Centre": 1498.5,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 461.51,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 211.21,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 102.51,
		},
		{
			Country: "Malaysia",
			"Meal, Inexpensive Restaurant": 27.58,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 183.85,
			"Domestic Beer  (0.5 liter draught)": 34.47,
			"Gasoline  (1 liter)": 4.73,
			"Apartment  (1 bedroom)  in City Centre": 3818.49,
			"Apartment  (1 bedroom)  Outside of Centre": 2658.65,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 467.8,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 272.41,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 91.92,
		},
		{
			Country: "Switzerland",
			"Meal, Inexpensive Restaurant": 300.13,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 1320.59,
			"Domestic Beer  (0.5 liter draught)": 84.04,
			"Gasoline  (1 liter)": 23.07,
			"Apartment  (1 bedroom)  in City Centre": 19919.68,
			"Apartment  (1 bedroom)  Outside of Centre": 15777.53,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2806.4,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 619.69,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 724.17,
		},
		{
			Country: "Bolivia",
			"Meal, Inexpensive Restaurant": 31.22,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 241.93,
			"Domestic Beer  (0.5 liter draught)": 18.73,
			"Gasoline  (1 liter)": 5.91,
			"Apartment  (1 bedroom)  in City Centre": 3226.8,
			"Apartment  (1 bedroom)  Outside of Centre": 2342.06,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 478.87,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 498.4,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 239.33,
		},
		{
			Country: "Egypt",
			"Meal, Inexpensive Restaurant": 34.84,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 174.18,
			"Domestic Beer  (0.5 liter draught)": 17.42,
			"Gasoline  (1 liter)": 3.42,
			"Apartment  (1 bedroom)  in City Centre": 1596.59,
			"Apartment  (1 bedroom)  Outside of Centre": 945.89,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 266.74,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 119.11,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 102.1,
		},
		{
			Country: "Morocco",
			"Meal, Inexpensive Restaurant": 36.78,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 212.78,
			"Domestic Beer  (0.5 liter draught)": 26.27,
			"Gasoline  (1 liter)": 14.3,
			"Apartment  (1 bedroom)  in City Centre": 3281.62,
			"Apartment  (1 bedroom)  Outside of Centre": 1906.26,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 411.31,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 354.89,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 104.11,
		},
		{
			Country: "China",
			"Meal, Inexpensive Restaurant": 36.96,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 295.64,
			"Domestic Beer  (0.5 liter draught)": 10.35,
			"Gasoline  (1 liter)": 12.54,
			"Apartment  (1 bedroom)  in City Centre": 5436.14,
			"Apartment  (1 bedroom)  Outside of Centre": 3300.48,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 582.02,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 130.66,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 159.42,
		},
		{
			Country: "Kenya",
			"Meal, Inexpensive Restaurant": 37,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 296.03,
			"Domestic Beer  (0.5 liter draught)": 18.5,
			"Gasoline  (1 liter)": 12.29,
			"Apartment  (1 bedroom)  in City Centre": 2270.98,
			"Apartment  (1 bedroom)  Outside of Centre": 1299.43,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 241.69,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 394.4,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 148.01,
		},
		{
			Country: "Iran",
			"Meal, Inexpensive Restaurant": 37.69,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 258.46,
			"Domestic Beer  (0.5 liter draught)": "-",
			"Gasoline  (1 liter)": 5.88,
			"Apartment  (1 bedroom)  in City Centre": 3832.68,
			"Apartment  (1 bedroom)  Outside of Centre": 2505.71,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 191,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 124.81,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 23.07,
		},
		{
			Country: "Ecuador",
			"Meal, Inexpensive Restaurant": 37.69,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 376.92,
			"Domestic Beer  (0.5 liter draught)": 21.54,
			"Gasoline  (1 liter)": 7.42,
			"Apartment  (1 bedroom)  in City Centre": 3995.79,
			"Apartment  (1 bedroom)  Outside of Centre": 2908.66,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 497.08,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 411.28,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 129.72,
		},
		{
			Country: "Philippines",
			"Meal, Inexpensive Restaurant": 37.89,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 227.32,
			"Domestic Beer  (0.5 liter draught)": 13.26,
			"Gasoline  (1 liter)": 13.58,
			"Apartment  (1 bedroom)  in City Centre": 3489.51,
			"Apartment  (1 bedroom)  Outside of Centre": 1896.87,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1057.37,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 365.81,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 471.61,
		},
		{
			Country: "Taiwan",
			"Meal, Inexpensive Restaurant": 40.48,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 337.32,
			"Domestic Beer  (0.5 liter draught)": 20.24,
			"Gasoline  (1 liter)": 10.38,
			"Apartment  (1 bedroom)  in City Centre": 4621.5,
			"Apartment  (1 bedroom)  Outside of Centre": 3497.33,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 877.42,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 247.05,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 358.76,
		},
		{
			Country: "Colombia",
			"Meal, Inexpensive Restaurant": 41.19,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 247.13,
			"Domestic Beer  (0.5 liter draught)": 12.36,
			"Gasoline  (1 liter)": 7,
			"Apartment  (1 bedroom)  in City Centre": 3303.12,
			"Apartment  (1 bedroom)  Outside of Centre": 2741.84,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 848.33,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 269.18,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 87.9,
		},
		{
			Country: "Syria",
			"Meal, Inexpensive Restaurant": 43.08,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 204.08,
			"Domestic Beer  (0.5 liter draught)": 16.69,
			"Gasoline  (1 liter)": 12.84,
			"Apartment  (1 bedroom)  in City Centre": 1734.07,
			"Apartment  (1 bedroom)  Outside of Centre": 1063.29,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 360.8,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 313.63,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 97.08,
		},
		{
			Country: "Peru",
			"Meal, Inexpensive Restaurant": 43.52,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 246.64,
			"Domestic Beer  (0.5 liter draught)": 23.21,
			"Gasoline  (1 liter)": 16.18,
			"Apartment  (1 bedroom)  in City Centre": 4201.24,
			"Apartment  (1 bedroom)  Outside of Centre": 2737.14,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 692.33,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 310.62,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 123.59,
		},
		{
			Country: "Kosovo (Disputed Territory)",
			"Meal, Inexpensive Restaurant": 45.96,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 229.79,
			"Domestic Beer  (0.5 liter draught)": 20.68,
			"Gasoline  (1 liter)": 17.31,
			"Apartment  (1 bedroom)  in City Centre": 3467.22,
			"Apartment  (1 bedroom)  Outside of Centre": 2526.2,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 942.56,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 224.99,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 114.78,
		},
		{
			Country: "Turkey",
			"Meal, Inexpensive Restaurant": 47.87,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 199.47,
			"Domestic Beer  (0.5 liter draught)": 19.95,
			"Gasoline  (1 liter)": 10.81,
			"Apartment  (1 bedroom)  in City Centre": 3855.58,
			"Apartment  (1 bedroom)  Outside of Centre": 2731.6,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 609.77,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 89.31,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 64.09,
		},
		{
			Country: "Guatemala",
			"Meal, Inexpensive Restaurant": 47.94,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 376.69,
			"Domestic Beer  (0.5 liter draught)": 23.97,
			"Gasoline  (1 liter)": 11.77,
			"Apartment  (1 bedroom)  in City Centre": 5224.9,
			"Apartment  (1 bedroom)  Outside of Centre": 3704.96,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 602.59,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 505.79,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 159.81,
		},
		{
			Country: "Bosnia And Herzegovina",
			"Meal, Inexpensive Restaurant": 52.88,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 282.05,
			"Domestic Beer  (0.5 liter draught)": 17.63,
			"Gasoline  (1 liter)": 16.9,
			"Apartment  (1 bedroom)  in City Centre": 2454.07,
			"Apartment  (1 bedroom)  Outside of Centre": 1806.47,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1659.62,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 259.13,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 193.91,
		},
		{
			Country: "Iraq",
			"Meal, Inexpensive Restaurant": 53.85,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 236.92,
			"Domestic Beer  (0.5 liter draught)": 21.54,
			"Gasoline  (1 liter)": 5.99,
			"Apartment  (1 bedroom)  in City Centre": 3849.57,
			"Apartment  (1 bedroom)  Outside of Centre": 2345.71,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1013.86,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 355.31,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 307.85,
		},
		{
			Country: "Uzbekistan",
			"Meal, Inexpensive Restaurant": 53.85,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 236.92,
			"Domestic Beer  (0.5 liter draught)": 10.77,
			"Gasoline  (1 liter)": 9.38,
			"Apartment  (1 bedroom)  in City Centre": 5278.57,
			"Apartment  (1 bedroom)  Outside of Centre": 3537.06,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 423.69,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 152.39,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 47.23,
		},
		{
			Country: "North Macedonia",
			"Meal, Inexpensive Restaurant": 55.95,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 223.81,
			"Domestic Beer  (0.5 liter draught)": 18.65,
			"Gasoline  (1 liter)": 15.59,
			"Apartment  (1 bedroom)  in City Centre": 2419.32,
			"Apartment  (1 bedroom)  Outside of Centre": 1791.09,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1339.8,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 190.47,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 186.33,
		},
		{
			Country: "Oman",
			"Meal, Inexpensive Restaurant": 56.02,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 301.11,
			"Domestic Beer  (0.5 liter draught)": 112.04,
			"Gasoline  (1 liter)": 6.65,
			"Apartment  (1 bedroom)  in City Centre": 6083.78,
			"Apartment  (1 bedroom)  Outside of Centre": 4279,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1087.8,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 843.42,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 612.73,
		},
		{
			Country: "Brazil",
			"Meal, Inexpensive Restaurant": 59.72,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 309.68,
			"Domestic Beer  (0.5 liter draught)": 19.91,
			"Gasoline  (1 liter)": 13.76,
			"Apartment  (1 bedroom)  in City Centre": 3439.66,
			"Apartment  (1 bedroom)  Outside of Centre": 2260.64,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 831.06,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 225.65,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 241.22,
		},
		{
			Country: "Russia",
			"Meal, Inexpensive Restaurant": 66.68,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 311.15,
			"Domestic Beer  (0.5 liter draught)": 16.67,
			"Gasoline  (1 liter)": 5.78,
			"Apartment  (1 bedroom)  in City Centre": 3554.27,
			"Apartment  (1 bedroom)  Outside of Centre": 2373.01,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 907.29,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 60.46,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 77.14,
		},
		{
			Country: "Jamaica",
			"Meal, Inexpensive Restaurant": 69.73,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 557.8,
			"Domestic Beer  (0.5 liter draught)": 24.4,
			"Gasoline  (1 liter)": 14.21,
			"Apartment  (1 bedroom)  in City Centre": 4961.9,
			"Apartment  (1 bedroom)  Outside of Centre": 3185.17,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1291.97,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 488.23,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 202.9,
		},
		{
			Country: "Kuwait",
			"Meal, Inexpensive Restaurant": 69.75,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 558,
			"Domestic Beer  (0.5 liter draught)": "-",
			"Gasoline  (1 liter)": 3.65,
			"Apartment  (1 bedroom)  in City Centre": 9389.69,
			"Apartment  (1 bedroom)  Outside of Centre": 7193.88,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 484.56,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 324.34,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 240.02,
		},
		{
			Country: "Argentina",
			"Meal, Inexpensive Restaurant": 71.4,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 269.23,
			"Domestic Beer  (0.5 liter draught)": 20.46,
			"Gasoline  (1 liter)": 9.23,
			"Apartment  (1 bedroom)  in City Centre": 3036.81,
			"Apartment  (1 bedroom)  Outside of Centre": 2196.83,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 472.77,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 206.27,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 251.51,
		},
		{
			Country: "Saudi Arabia",
			"Meal, Inexpensive Restaurant": 71.78,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 488.09,
			"Domestic Beer  (0.5 liter draught)": "-",
			"Gasoline  (1 liter)": 6.6,
			"Apartment  (1 bedroom)  in City Centre": 5047.08,
			"Apartment  (1 bedroom)  Outside of Centre": 3826.85,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1114.18,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 773.17,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 383.88,
		},
		{
			Country: "Mauritius",
			"Meal, Inexpensive Restaurant": 71.99,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 359.93,
			"Domestic Beer  (0.5 liter draught)": 23.98,
			"Gasoline  (1 liter)": 16.52,
			"Apartment  (1 bedroom)  in City Centre": 4519.29,
			"Apartment  (1 bedroom)  Outside of Centre": 3125.73,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 632.46,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 340.95,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 231.96,
		},
		{
			Country: "Japan",
			"Meal, Inexpensive Restaurant": 72.92,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 364.62,
			"Domestic Beer  (0.5 liter draught)": 29.17,
			"Gasoline  (1 liter)": 11.99,
			"Apartment  (1 bedroom)  in City Centre": 6550.64,
			"Apartment  (1 bedroom)  Outside of Centre": 4213.65,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1724.13,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 348.96,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 296.56,
		},
		{
			Country: "Ukraine",
			"Meal, Inexpensive Restaurant": 73.01,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 292.03,
			"Domestic Beer  (0.5 liter draught)": 11.68,
			"Gasoline  (1 liter)": 15.23,
			"Apartment  (1 bedroom)  in City Centre": 3847.54,
			"Apartment  (1 bedroom)  Outside of Centre": 2494.9,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 943.76,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 60.55,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 65.67,
		},
		{
			Country: "South Korea",
			"Meal, Inexpensive Restaurant": 73.11,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 406.16,
			"Domestic Beer  (0.5 liter draught)": 32.49,
			"Gasoline  (1 liter)": 14.29,
			"Apartment  (1 bedroom)  in City Centre": 5404.98,
			"Apartment  (1 bedroom)  Outside of Centre": 3903.24,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1771.45,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 231.93,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 542.43,
		},
		{
			Country: "Palestine",
			"Meal, Inexpensive Restaurant": 73.55,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 282.9,
			"Domestic Beer  (0.5 liter draught)": 29.7,
			"Gasoline  (1 liter)": 18.98,
			"Apartment  (1 bedroom)  in City Centre": 3260.78,
			"Apartment  (1 bedroom)  Outside of Centre": 2511.68,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1011.7,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 446.24,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 142.51,
		},
		{
			Country: "Albania",
			"Meal, Inexpensive Restaurant": 75.22,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 376.11,
			"Domestic Beer  (0.5 liter draught)": 21.49,
			"Gasoline  (1 liter)": 21.3,
			"Apartment  (1 bedroom)  in City Centre": 4057.25,
			"Apartment  (1 bedroom)  Outside of Centre": 2718.12,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 949.35,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 176.8,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 164.53,
		},
		{
			Country: "Dominican Republic",
			"Meal, Inexpensive Restaurant": 76,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 474.99,
			"Domestic Beer  (0.5 liter draught)": 28.5,
			"Gasoline  (1 liter)": 13.63,
			"Apartment  (1 bedroom)  in City Centre": 5178.16,
			"Apartment  (1 bedroom)  Outside of Centre": 2718.31,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 585.41,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 503.67,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 198.14,
		},
		{
			Country: "Jordan",
			"Meal, Inexpensive Restaurant": 76.03,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 456.19,
			"Domestic Beer  (0.5 liter draught)": 68.43,
			"Gasoline  (1 liter)": 14.63,
			"Apartment  (1 bedroom)  in City Centre": 3374.72,
			"Apartment  (1 bedroom)  Outside of Centre": 2550.34,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 928.18,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 377.87,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 174.61,
		},
		{
			Country: "Serbia",
			"Meal, Inexpensive Restaurant": 78.39,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 344.69,
			"Domestic Beer  (0.5 liter draught)": 22.54,
			"Gasoline  (1 liter)": 17.64,
			"Apartment  (1 bedroom)  in City Centre": 5657.63,
			"Apartment  (1 bedroom)  Outside of Centre": 3877.37,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1608.07,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 268.26,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 146.33,
		},
		{
			Country: "Slovakia",
			"Meal, Inexpensive Restaurant": 80.43,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 402.13,
			"Domestic Beer  (0.5 liter draught)": 20.68,
			"Gasoline  (1 liter)": 18.29,
			"Apartment  (1 bedroom)  in City Centre": 6029.87,
			"Apartment  (1 bedroom)  Outside of Centre": 4904.04,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2355.92,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 200.48,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 371.11,
		},
		{
			Country: "Kazakhstan",
			"Meal, Inexpensive Restaurant": 80.64,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 345.61,
			"Domestic Beer  (0.5 liter draught)": 13.82,
			"Gasoline  (1 liter)": 4.98,
			"Apartment  (1 bedroom)  in City Centre": 6024.94,
			"Apartment  (1 bedroom)  Outside of Centre": 4161.86,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 559.42,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 130.17,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 107.48,
		},
		{
			Country: "Romania",
			"Meal, Inexpensive Restaurant": 80.93,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 385,
			"Domestic Beer  (0.5 liter draught)": 18.5,
			"Gasoline  (1 liter)": 17.52,
			"Apartment  (1 bedroom)  in City Centre": 4078.64,
			"Apartment  (1 bedroom)  Outside of Centre": 3034.98,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1486.68,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 93.08,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 81.1,
		},
		{
			Country: "Azerbaijan",
			"Meal, Inexpensive Restaurant": 82.35,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 316.74,
			"Domestic Beer  (0.5 liter draught)": 12.67,
			"Gasoline  (1 liter)": 6.53,
			"Apartment  (1 bedroom)  in City Centre": 3594.08,
			"Apartment  (1 bedroom)  Outside of Centre": 2162.1,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 533.77,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 168.93,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 140.11,
		},
		{
			Country: "Hong Kong (China)",
			"Meal, Inexpensive Restaurant": 82.58,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 688.15,
			"Domestic Beer  (0.5 liter draught)": 68.81,
			"Gasoline  (1 liter)": 31.19,
			"Apartment  (1 bedroom)  in City Centre": 25232.13,
			"Apartment  (1 bedroom)  Outside of Centre": 18235.95,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2493.39,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 240,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 207.82,
		},
		{
			Country: "South Africa",
			"Meal, Inexpensive Restaurant": 85.23,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 340.93,
			"Domestic Beer  (0.5 liter draught)": 19.89,
			"Gasoline  (1 liter)": 12.98,
			"Apartment  (1 bedroom)  in City Centre": 4331.74,
			"Apartment  (1 bedroom)  Outside of Centre": 3471.15,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1049.66,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 461.42,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 316.42,
		},
		{
			Country: "Panama",
			"Meal, Inexpensive Restaurant": 86.15,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 592.31,
			"Domestic Beer  (0.5 liter draught)": 21.54,
			"Gasoline  (1 liter)": 11.97,
			"Apartment  (1 bedroom)  in City Centre": 8837.31,
			"Apartment  (1 bedroom)  Outside of Centre": 5466.95,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1014.99,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 501.37,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 337.21,
		},
		{
			Country: "Poland",
			"Meal, Inexpensive Restaurant": 86.56,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 395.71,
			"Domestic Beer  (0.5 liter draught)": 29.68,
			"Gasoline  (1 liter)": 16.99,
			"Apartment  (1 bedroom)  in City Centre": 7200.52,
			"Apartment  (1 bedroom)  Outside of Centre": 5768.73,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 2471.83,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 143.96,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 138.55,
		},
		{
			Country: "Bulgaria",
			"Meal, Inexpensive Restaurant": 88.14,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 411.34,
			"Domestic Beer  (0.5 liter draught)": 20.57,
			"Gasoline  (1 liter)": 16.43,
			"Apartment  (1 bedroom)  in City Centre": 3976.17,
			"Apartment  (1 bedroom)  Outside of Centre": 2950.02,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1184.29,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 134.85,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 173.27,
		},
		{
			Country: "Qatar",
			"Meal, Inexpensive Restaurant": 88.65,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 591.02,
			"Domestic Beer  (0.5 liter draught)": "-",
			"Gasoline  (1 liter)": 6.13,
			"Apartment  (1 bedroom)  in City Centre": 17831.15,
			"Apartment  (1 bedroom)  Outside of Centre": 10536.54,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1199.19,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 948.11,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 573.29,
		},
		{
			Country: "Czech Republic",
			"Meal, Inexpensive Restaurant": 88.88,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 397.64,
			"Domestic Beer  (0.5 liter draught)": 21.05,
			"Gasoline  (1 liter)": 19.44,
			"Apartment  (1 bedroom)  in City Centre": 7780.92,
			"Apartment  (1 bedroom)  Outside of Centre": 6239.47,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 3095.18,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 245.66,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 338.55,
		},
		{
			Country: "Hungary",
			"Meal, Inexpensive Restaurant": 89.87,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 449.33,
			"Domestic Beer  (0.5 liter draught)": 20.97,
			"Gasoline  (1 liter)": 17.3,
			"Apartment  (1 bedroom)  in City Centre": 5001.64,
			"Apartment  (1 bedroom)  Outside of Centre": 3957.34,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1559.91,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 166.85,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 298.89,
		},
		{
			Country: "Chile",
			"Meal, Inexpensive Restaurant": 91.27,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 486.77,
			"Domestic Beer  (0.5 liter draught)": 36.51,
			"Gasoline  (1 liter)": 15.42,
			"Apartment  (1 bedroom)  in City Centre": 4958.28,
			"Apartment  (1 bedroom)  Outside of Centre": 4175.72,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1349.95,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 269.28,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 133.17,
		},
		{
			Country: "Montenegro",
			"Meal, Inexpensive Restaurant": 91.92,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 402.13,
			"Domestic Beer  (0.5 liter draught)": 25.28,
			"Gasoline  (1 liter)": 17.2,
			"Apartment  (1 bedroom)  in City Centre": 6182.68,
			"Apartment  (1 bedroom)  Outside of Centre": 4560.33,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1228,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 288.3,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 236.6,
		},
		{
			Country: "Mexico",
			"Meal, Inexpensive Restaurant": 94.68,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 378.71,
			"Domestic Beer  (0.5 liter draught)": 25.25,
			"Gasoline  (1 liter)": 14.48,
			"Apartment  (1 bedroom)  in City Centre": 5977.38,
			"Apartment  (1 bedroom)  Outside of Centre": 3818.74,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 682.02,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 326.18,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 266.69,
		},
		{
			Country: "United Arab Emirates",
			"Meal, Inexpensive Restaurant": 96.02,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 586.4,
			"Domestic Beer  (0.5 liter draught)": 114.35,
			"Gasoline  (1 liter)": 9.74,
			"Apartment  (1 bedroom)  in City Centre": 13512.43,
			"Apartment  (1 bedroom)  Outside of Centre": 9491.24,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1815.37,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 1079.8,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 638.66,
		},
		{
			Country: "Venezuela",
			"Meal, Inexpensive Restaurant": 96.92,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 538.46,
			"Domestic Beer  (0.5 liter draught)": 16.15,
			"Gasoline  (1 liter)": 5.38,
			"Apartment  (1 bedroom)  in City Centre": 2194.69,
			"Apartment  (1 bedroom)  Outside of Centre": 1997.69,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 205.37,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 417.09,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 161.54,
		},
		{
			Country: "Armenia",
			"Meal, Inexpensive Restaurant": 98.18,
			"Meal for 2 People,  Mid-range Restaurant, Three-course": 561.01,
			"Domestic Beer  (0.5 liter draught)": 18.23,
			"Gasoline  (1 liter)": 13.66,
			"Apartment  (1 bedroom)  in City Centre": 10783.05,
			"Apartment  (1 bedroom)  Outside of Centre": 7163.27,
			"Basic  (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment": 1335.02,
			"Internet  (60 Mbps or More, Unlimited Data, Cable/ADSL)": 211.31,
			"Mobile Phone Monthly Plan with Calls and 10GB+ Data": 108.95,
		},
	],
	countriesWithContinents: [
		{ country: "Costa Rica", continent: "North America" },
		{ country: "Portugal", continent: "Europe" },
		{ country: "Belarus", continent: "Europe" },
		{ country: "Croatia", continent: "Europe" },
		{ country: "Georgia", continent: "Asia" },
		{ country: "Latvia", continent: "Europe" },
		{ country: "Estonia", continent: "Europe" },
		{ country: "Slovenia", continent: "Europe" },
		{ country: "Lithuania", continent: "Europe" },
		{ country: "Sweden", continent: "Europe" },
		{ country: "Singapore", continent: "Asia" },
		{ country: "Puerto Rico", continent: "North America" },
		{ country: "Greece", continent: "Europe" },
		{ country: "Germany", continent: "Europe" },
		{ country: "Spain", continent: "Europe" },
		{ country: "Finland", continent: "Europe" },
		{ country: "New Zealand", continent: "Oceania" },
		{ country: "Uruguay", continent: "South America" },
		{ country: "Indonesia", continent: "Asia" },
		{ country: "Cyprus", continent: "Europe" },
		{ country: "Austria", continent: "Europe" },
		{ country: "Italy", continent: "Europe" },
		{ country: "Malta", continent: "Europe" },
		{ country: "Netherlands", continent: "Europe" },
		{ country: "Ireland", continent: "Europe" },
		{ country: "France", continent: "Europe" },
		{ country: "Australia", continent: "Oceania" },
		{ country: "Canada", continent: "North America" },
		{ country: "Pakistan", continent: "Asia" },
		{ country: "Bangladesh", continent: "Asia" },
		{ country: "Belgium", continent: "Europe" },
		{ country: "Israel", continent: "Asia" },
		{ country: "Norway", continent: "Europe" },
		{ country: "United Kingdom", continent: "Europe" },
		{ country: "Luxembourg", continent: "Europe" },
		{ country: "United States", continent: "North America" },
		{ country: "Denmark", continent: "Europe" },
		{ country: "Vietnam", continent: "Asia" },
		{ country: "Nepal", continent: "Asia" },
		{ country: "Algeria", continent: "Africa" },
		{ country: "Thailand", continent: "Asia" },
		{ country: "Sri Lanka", continent: "Asia" },
		{ country: "India", continent: "Asia" },
		{ country: "Tunisia", continent: "Africa" },
		{ country: "Malaysia", continent: "Asia" },
		{ country: "Switzerland", continent: "Europe" },
		{ country: "Bolivia", continent: "South America" },
		{ country: "Egypt", continent: "Africa" },
		{ country: "Morocco", continent: "Africa" },
		{ country: "China", continent: "Asia" },
		{ country: "Kenya", continent: "Africa" },
		{ country: "Iran", continent: "Asia" },
		{ country: "Ecuador", continent: "South America" },
		{ country: "Philippines", continent: "Asia" },
		{ country: "Taiwan", continent: "Asia" },
		{ country: "Colombia", continent: "South America" },
		{ country: "Syria", continent: "Asia" },
		{ country: "Peru", continent: "South America" },
		{ country: "Kosovo (Disputed Territory)", continent: "Europe" },
		{ country: "Turkey", continent: "Asia" },
		{ country: "Guatemala", continent: "North America" },
		{ country: "Bosnia And Herzegovina", continent: "Europe" },
		{ country: "Iraq", continent: "Asia" },
		{ country: "Uzbekistan", continent: "Asia" },
		{ country: "North Macedonia", continent: "Europe" },
		{ country: "Oman", continent: "Asia" },
		{ country: "Brazil", continent: "South America" },
		{ country: "Russia", continent: "Europe/Asia" },
		{ country: "Jamaica", continent: "North America" },
		{ country: "Kuwait", continent: "Asia" },
		{ country: "Argentina", continent: "South America" },
		{ country: "Saudi Arabia", continent: "Asia" },
		{ country: "Mauritius", continent: "Africa" },
		{ country: "Japan", continent: "Asia" },
		{ country: "Ukraine", continent: "Europe" },
		{ country: "South Korea", continent: "Asia" },
		{ country: "Palestine", continent: "Asia" },
		{ country: "Albania", continent: "Europe" },
		{ country: "Dominican Republic", continent: "North America" },
		{ country: "Jordan", continent: "Asia" },
		{ country: "Serbia", continent: "Europe" },
		{ country: "Slovakia", continent: "Europe" },
		{ country: "Kazakhstan", continent: "Asia" },
		{ country: "Romania", continent: "Europe" },
		{ country: "Azerbaijan", continent: "Asia" },
		{ country: "Hong Kong (China)", continent: "Asia" },
		{ country: "South Africa", continent: "Africa" },
		{ country: "Panama", continent: "North America" },
		{ country: "Poland", continent: "Europe" },
		{ country: "Bulgaria", continent: "Europe" },
		{ country: "Qatar", continent: "Asia" },
		{ country: "Czech Republic", continent: "Europe" },
		{ country: "Hungary", continent: "Europe" },
		{ country: "Chile", continent: "South America" },
		{ country: "Montenegro", continent: "Europe" },
		{ country: "Mexico", continent: "North America" },
		{ country: "United Arab Emirates", continent: "Asia" },
		{ country: "Venezuela", continent: "South America" },
		{ country: "Armenia", continent: "Asia" },
	],
};
